version: '3'
services:
        dbos:
          image: mysql:latest
          restart: always
          environment:
                MYSQL_ROOT_PASSWORD: rootpass
                MYSQL_USER: Akarsh
                MYSQL_PASSWORD: redhat
                MYSQL_DATABASE: db
          volumes:
                - mysql_storage_new:/var/lib/html

        nextcloudos:
          image: nextcloud:latest
          environment:
                POSTGRES_DB: db
                POSTGRES_USER: Akarsh
                POSTGRES_PASSWORD: redhat
                POSTGRES_HOST: dbos
                NEXTCLOUD_ADMIN_USER: Akarsh
                NEXTCLOUD_ADMIN_PASSWORD: asdf1234
          restart: always
          volumes:
                - next_cloudstorage:/var/www/html/data

          depends_on:
                - dbos
          ports:
                - 8080:80
volumes:
        next_cloudstorage:
        mysql_storage_new:




